package am2.preloader;

import am2.LogHelper;
import com.google.common.eventbus.EventBus;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;

import java.io.File;
import java.util.Arrays;
import java.util.Map;


public class AM2PreloaderContainer extends DummyModContainer implements IFMLLoadingPlugin{

	private final String[] asmTransformers = new String[]{"am2.preloader.AccessTransformers", "am2.preloader.BytecodeTransformers"};
	private final ModMetadata md = new ModMetadata();

	public static boolean foundThaumcraft = false;
	public static boolean foundOptifine = false;
	public static boolean foundDragonAPI = false;

	public AM2PreloaderContainer(){

		LogHelper.info("Core initializing...stand back!  I'm going to try MAGIC!");

		md.autogenerated = true;
		md.credits = "Mithion, AlgorithmX2, Sunstrike";
		md.modId = getModId();
		md.version = getVersion();
		md.name = getName();
		md.authorList = Arrays.asList("Mithion", "AlgorithmX2", "Sunstrike");
	}

	@Override
	public String getModId(){
		return "AM2-Preloader";
	}

	@Override
	public String getName(){
		return "AMCore";
	}

	@Override
	public String getVersion(){
		return "0.0.2";
	}

	@Override
	public String getDisplayVersion(){
		return getVersion();
	}

	@Override
	public ModMetadata getMetadata(){
		return md;
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller){
		bus.register(this);
		return true;
	}

	@Override
	public String[] getASMTransformerClass(){
		return asmTransformers;
	}

	@Override
	public String getModContainerClass(){
		return "am2.preloader.AM2PreloaderContainer";
	}

	@Override
	public String getSetupClass(){
		return null;
	}

	@Override
	public void injectData(Map<String, Object> data){
		File loc = (File)data.get("mcLocation");

		LogHelper.trace("MC located at: " + loc.getAbsolutePath());

		File mcFolder = new File(loc.getAbsolutePath() + File.separatorChar + "mods");
		File[] subfiles = mcFolder.listFiles();
		for (File f : subfiles){
			if (f.getName() != null){
				if (f.getName().toLowerCase().contains("thaumcraft")){
					LogHelper.info("Core: Located Thaumcraft");
					foundThaumcraft = true;
				}else if (f.getName().toLowerCase().contains("optifine")){
					LogHelper.info("Core: Located Optifine");
					foundOptifine = true;
				}else if (f.getName().toLowerCase().contains("dragonapi")){
					LogHelper.info("Core: Located DragonAPI");
					foundDragonAPI = true;
				}
			}
		}
	}

	@Override
	public String getAccessTransformerClass(){
		return null;
	}

}
